### ISSUE TITLE
QUnit Example error

### ISSUE THREAD

**Issue by dipscom** [google-developer-training/pwa-training-labs#5]
In _fetch-api-lab/app/test/test.html_ Line:71 error is a `string` so
```
assert.ok(error.message.indexOf('File not found'),
          'bad responses throw error that contains response.statusText');
```
is a TypeError is it cannot read property `indexOf` of undefined which is breaking all subsequent tests. 

Removing `message.indexOf` from the `assert.ok` prevents the error.

**Comment by DavidScales** [comment]
Hi @dipscom 

Thanks for filing a bug! 

It looks like this test assumed that an `Error` object would be thrown in `validateResponse`, rather than a string. I've made the test more robust by checking for string errors as well in 05bbdac. 

I also found a typo in a method call (`assert.ok` was being called as `assert.okay`) within the same test, which was also causing a TypeError. I have corrected that in 6a018d5. So thanks for helping me find that as well! ;)

Let me know if you find anything else!
